module.exports = {
	ignores: [(commit) => commit.includes("init")],
	extends: ["@commitlint/config-conventional"],
	rules: {
		"body-leading-blank": [2, "always"],
		"footer-leading-blank": [1, "always"],
		"header-max-length": [2, "always", 108],
		"subject-empty": [2, "never"],
		"type-empty": [2, "never"],
		"type-enum": [
			2,
			"always",
			[
				"feat" /* 新功能 */,
				"fix" /* bug */,
				"perf" /* 性能优化 */,
				"style" /* 格式 */,
				"docs" /* 文档 */,
				"test" /* 测试 */,
				"refactor" /* 重构 */,
				"build" /* 打包 */,
				"ci" /* 自动化脚本的意思 */,
				"chore" /* 构建过程或辅助工具的变动 */,
				"revert" /* 恢复 */,
				"wip" /* 正在进行中的工作 */,
				"workflow" /* 工作流程 */,
				"types" /* 添加类型 */,
				"release" /* 发版 */,
			],
		],
	},
};
